### PR TITLE
Feat: sorting and filter

### PR DESCRIPTION
**Pull request by gauravsinhaweb**

### CODE REVIEW

**Review by Ankur9669 — APPROVED** [review]
The Functionalities are working fine and great work on the UI

Suggestions: 
Change the favicon and title of the app

On Bigger screens it will look like this
image

**Review by simran61 — APPROVED** [review]
Look good
Clean code

**Review by mehulsatardekar — APPROVED** [review]
functionality working fine good work on UI

**Comment by gauravsinhaweb** [comment]
> The Functionalities are working fine and great work on the UI
> 
> Suggestions: Change the favicon and title of the app
> 
> On Bigger screens it will look like this image

fixed screen size for larger screens

**Comment by shivamSspirit** [comment]
lgtm

**Pull request merged**
